definitions:
  article.listResult:
    properties:
      category:
        type: integer
      count:
        type: integer
      list:
        items:
          $ref: '#/definitions/data.Article'
        type: array
      page:
        type: integer
      search:
        type: string
      timeline:
        type: integer
      total:
        type: number
    type: object
  data.Article:
    properties:
      author:
        type: string
      cover:
        type: string
      ctime:
        type: string
      id:
        type: integer
      intro:
        type: string
      raw:
        type: string
      timeline:
        type: integer
      title:
        type: string
      type:
        type: integer
    type: object
info:
  contact: {}
  description: Golang 脚手架，Go 简单，Go 直接
  license: {}
  termsOfService: https://github.com/armnerd/go-skeleton
  title: go-skeleton
  version: "1.0"
paths:
  /api/article/info:
    post:
      parameters:
      - description: 文章 id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/data.Article'
      summary: 文章详情
  /api/article/list:
    post:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 分类
        in: query
        name: category
        type: integer
      - description: 时间轴
        in: query
        name: timeline
        type: integer
      - description: 搜索
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/article.listResult'
      summary: 文章列表
swagger: "2.0"
